//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektP4
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int id { get; set; }
        public int train_id { get; set; }
        public int origin_station_id { get; set; }
        public int destination_station_id { get; set; }
        public System.DateTime departure_time { get; set; }
        public System.DateTime arrival_time { get; set; }
    
        public virtual station station { get; set; }
        public virtual station station1 { get; set; }
        public virtual train train { get; set; }
    }
}
